### ISSUE TITLE
Learning 2D interactions

### ISSUE THREAD

**Issue by atemysemicolon** [pystruct/pystruct#135]
I am trying to reproduce the sample code as in *plot_grid_crf.py* with my custom data. My array X is of the shape (2,720,960,12), having two training samples of two images of sizes 720(rows)x960(colums) and class-wise probabilities being along the final axis(3). Similarly my array Y is (2,720,960) having pixel wise ground truth. 

When I define the clf and crf objects the same way as the sample code, I get the following error  : 
```
Traceback (most recent call last):

  File "<ipython-input-5-3c2334b8ac36>", line 1, in <module>
    runfile('/home/prassanna/Development/workspace/Semantic-texton-forests/scripts/tempcrf.py', wdir='/home/prassanna/Development/workspace/Semantic-texton-forests/scripts')

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 601, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 73, in execfile
    builtins.execfile(filename, *where)

  File "/home/prassanna/Development/workspace/Semantic-texton-forests/scripts/tempcrf.py", line 158, in <module>
    clf.fit(X, Y)

  File "/usr/local/lib/python2.7/dist-packages/pystruct/learners/one_slack_ssvm.py", line 440, in fit
    joint_feature_gt = self.model.batch_joint_feature(X, Y)

  File "/usr/local/lib/python2.7/dist-packages/pystruct/models/base.py", line 40, in batch_joint_feature
    joint_feature_ += self.joint_feature(x, y)

  File "/usr/local/lib/python2.7/dist-packages/pystruct/models/graph_crf.py", line 194, in joint_feature
    unary_marginals[gx, y] = 1

IndexError: index 3 is out of bounds for axis 1 with size 3

```

I tried the same with -1 *log probabilities instead of probabilities and the same issue again. However, it works great with your sample data. I do not understand what's causing the problem.

Any help would be appreciated...

-Semicolon Warrior

**Comment by amueller** [comment]
I think the issue is that your ``y`` contains labels ``1, 2, 3`` where the current code assumes ``0, 1, 2``. Can you check that please? I did not get around to fixing this yet :-/

**Comment by amueller** [comment]
A pull-request with a better warning if ``y`` doesn't contain the expected label would be welcome.

**Comment by atemysemicolon** [comment]
My bad, it was me, I didn't arrange the data right.
