### ISSUE TITLE
Parallel issue on Windows 8.1 64bit

### ISSUE THREAD

**Issue by pengsun** [pystruct/pystruct#155]
Hi,

Whenever the `Parallel` stuff is called it appears the following error (e.g., it shows up when I run the example `plot_objective_curve.py`):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 495, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\Python27\Lib\site-packages\pystruct\examples\plot_objective_curve.py", line 42, in <module>
    clf.fit(X, Y)
  File "C:\Python27\lib\site-packages\pystruct-0.2.3-py2.7-win-amd64.egg\pystruct\learners\one_slack_ssvm.py", line 448, in fit
    X, Y, joint_feature_gt, constraints)
  File "C:\Python27\lib\site-packages\pystruct-0.2.3-py2.7-win-amd64.egg\pystruct\learners\one_slack_ssvm.py", line 345, in _find_new_constraint
    for x, y in zip(X, Y))
  File "C:\Python27\lib\site-packages\sklearn\externals\joblib\parallel.py", line 619, in __call__
    self._pool = MemmapingPool(n_jobs, **poolargs)
  File "C:\Python27\lib\site-packages\sklearn\externals\joblib\pool.py", line 583, in __init__
    super(MemmapingPool, self).__init__(**poolargs)
  File "C:\Python27\lib\site-packages\sklearn\externals\joblib\pool.py", line 422, in __init__
    super(PicklingPool, self).__init__(**poolargs)
  File "C:\Python27\lib\multiprocessing\pool.py", line 159, in __init__
    self._repopulate_pool()
  File "C:\Python27\lib\multiprocessing\pool.py", line 223, in _repopulate_pool
    w.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
```

where the code leading to the error message is in `one_slack_ssvm.py`:
``` Python
    def _find_new_constraint(self, X, Y, joint_feature_gt, constraints, check=True):
        if self.n_jobs != 1:
            # do inference in parallel
            verbose = max(0, self.verbose - 3)
            Y_hat = Parallel(n_jobs=self.n_jobs, verbose=verbose)(
                delayed(loss_augmented_inference)(
                    self.model, x, y, self.w, relaxed=True)
                for x, y in zip(X, Y))
```

Any suggestion to fix this is appreciated, thanks :-)

**Comment by amueller** [comment]
Can you please try wrapping the content of the example into a  ``if __name__ == "__main__"`` block?
You could do ``n_jobs=1`` in the example, which would fix it but be slower.

**Comment by pengsun** [comment]
Hi @amueller ,

Thanks for you suggestion. Wrapping with `if __name__ == "__main__"` does not work: the file runs silently forever and never outputs anything (even the error message) .

But setting `n_jobs=1` does solve the problem and I can see the final figure. Maybe I need switch to Linux which would make life easier :-)

**Comment by amueller** [comment]
maybe @ogrisel has some time to give advice. I have no idea what is happening ;) Could be an issue with your blas? How did you install python / numpy?

**Comment by pengsun** [comment]
Hi,

I downloaded Python 2.7.8 windows installer from https://www.python.org/
Then I downloaded the `numpy‑1.9.2+mkl‑cp27‑none‑win_amd64.whl` from http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy and installed it by typing `pip install`.

I think the versions should meet the requirement?

**Comment by amueller** [comment]
yeah, that should be fine... How did you get cvxopt then?
I usually use anaconda, and you could try that and see if it works.

**Comment by pengsun** [comment]
This is fixed, closing.

Thanks @amueller for your help:-)
