### ISSUE TITLE
cvxopt is not an explicit dependency

### ISSUE THREAD

**Issue by nszceta** [pystruct/pystruct#159]
```
Traceback (most recent call last): 
  File "crftest.py", line 8, in <module>
    from pystruct.learners import NSlackSSVM
  File "/home/ubuntu/venv/lib/python3.4/site-packages/pystruct/learners/__init__.py", line 1, in <module>
    from .n_slack_ssvm import NSlackSSVM
  File "/home/ubuntu/venv/lib/python3.4/site-packages/pystruct/learners/n_slack_ssvm.py", line 12, in <module>
    import cvxopt
```

Resolved with `pip install cvxopt`

**Comment by amueller** [comment]
That is because cvxopt is hard to install (``pip install cvxopt`` will not reliably work) and it is an optional dependency. Only ``NSlackSSVM`` and ``OneSlackSSVM`` need it.
We could give a better error message maybe?

**Comment by nszceta** [comment]
Perhaps it would be possible to somehow offer a binary Python wheel of cvxopt? http://pythonwheels.com/
Just a thought.

**Comment by amueller** [comment]
that doesn't help linux users... and it is in anaconda.. I think it would be most helpful to have a conda package for pystruct maybe.
Though a wheel for cvxopt would be good too, if it doesn't exist yet.
I don't really have cycles for either at the moment, unfortunately.
